seed: 123
# Hyperparameters etc.
LEARNING_RATE: 0.00003
DECAY_RATE: 0.1
WEIGHT_DECAY: 0
BALANCED_DATASET: false
GPU: true
MODEL: 'Darknet20'
BATCH_SIZE: 256 # 64 in original paper but I don't have that much vram, grad accum?
DECAY_EPOCHS: 30
EPOCHS: 300
NUM_WORKERS: 12
PIN_MEMORY: true
LOAD_MODEL: false
LOAD_MODEL_FILE: 'weights/Darknet20/epoch033_1_397.pth.tar'
SAVE_MODEL: true
SAVE_MODEL_N: 5
SAVE_MODEL_DIR: 'weights'
DATASET_DIR: '/home/alex/datasets/imagenet'
MIN_IMAGES: 750
LOSS:  'My Entropy' # 'SVM' #