seed: 123
# Hyperparameters etc.
LEARNING_RATE: 0.00003
DECAY_RATE: 0.1
WEIGHT_DECAY: 0
BALANCED_DATASET: false
GPU: true
MODEL: 'VGG16'# 'Darknet'
BATCH_SIZE: 64
DECAY_EPOCHS: 30
EPOCHS: 300
NUM_WORKERS: 12
PIN_MEMORY: true
LOAD_MODEL: true
LOAD_MODEL_FILE: '/home/alex/Projects/object_detection/BackBones/weights/Darknet20/epoch065_1_282.pth.tar'
SAVE_MODEL: false
SAVE_MODEL_N: 5
SAVE_MODEL_DIR: 'weights'
DATASET_DIR: '/home/alex/datasets/PascalVOC'
MIN_IMAGES: 750
LOSS:  'My Entropy' # 'SVM' #
CSV_TRAIN: 'train.csv'
CSV_VAL: 'test.csv'